image: node:8.12.0
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@7.1.2
    - npm install
    - npm run buildProd
  artifacts:
    paths:
      - public
  only:
    - master
    - pages