swagger: '2.0'
info:
  description: This the API server for your forms. You will need to use a copy of the api key to authorize.
  version: 1.0.0
  title: formloco API
  termsOfService: https://formloco/terms/
  contact:
    email: polly@formloco.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
host: https://bluerockmicro.com/api
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: x-access-token
security:
  - ApiKeyAuth: []
paths:
  /api/cf0b63d7-642b-40dc-8251-e8b4470c2d5e/f80f8f84-197a-4849-a5b1-881630ccc66d/:
    post:
      tags:
        - Design Link 2
      summary: Add form data
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Form object
          required: true
          schema:
            $ref: '#/definitions/Design Link 2'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Design Link 2'
        '405':
          description: Invalid input
    put:
      tags:
        - Design Link 2
      summary: Update form data
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Form object
          required: true
          schema:
            $ref: '#/definitions/Design Link 2'
      responses:
        '200':
          description: Successful operation
        '405':
          description: Invalid input
    get:
      tags: 
        - Design Link 2
      summary: Get form data
      produces: 
        - application/json
      parameters:
      - in: path
        name: tenant_id
        description: Form and data storage identifier
        schema:
        type: string
      - in: path
        name: form_id
        description: Form identifier
        schema:
        type: string
      - in: body
        required: false
        schema:
          $ref: '#/definitions/Design Link 2'
      responses:
        '201':
          description: Success
    delete:
      tags:
        - Design Link 2
      summary: Delete form data
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: tenant_id
          description: Tenant ID
          schema:
            type: string
        - in: path
          name: form_id
          description: Form ID
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '405':
          description: Invalid input
    
definitions:
  Design Link 2:
    type: object
    properties:
      Design Link 2:
        type: object
        properties:
          id:
            type: string
          user_updated:
            type: string
          user_created:
            type: string
          user_archived:
            type: string
          date_updated:
            type: string
          date_archived:
            type: string
          date_created:
            type: string