swagger: '2.0'
info:
  description: This the API server for your forms. You will need to use a copy of the api key to authorize.
  version: 1.0.0
  title: formloco API
  termsOfService: https://formloco/terms/
  contact:
    email: polly@formloco.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
host: localhost:9002
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: x-access-token
security:
  - ApiKeyAuth: []
paths:
  /api/d1ec9c36-b1d9-4d6f-89d6-658dc324c2a1/b3d8719e-7ae0-4458-9e67-c64a8ab8c318/:
    post:
      tags:
        - teest
      summary: Add form data
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Form object
          required: true
          schema:
            $ref: '#/definitions/teest'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/teest'
        '405':
          description: Invalid input
    put:
      tags:
        - teest
      summary: Update form data
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Form object
          required: true
          schema:
            $ref: '#/definitions/teest'
      responses:
        '200':
          description: Successful operation
        '405':
          description: Invalid input
    get:
      tags: 
        - teest
      summary: Get form data
      produces: 
        - application/json
      parameters:
      - in: path
        name: tenant_id
        description: Form and data storage identifier
        schema:
        type: string
      - in: path
        name: form_id
        description: Form identifier
        schema:
        type: string
      - in: body
        required: false
        schema:
          $ref: '#/definitions/teest'
      responses:
        '201':
          description: Success
    delete:
      tags:
        - teest
      summary: Delete form data
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: tenant_id
          description: Tenant ID
          schema:
            type: string
        - in: path
          name: form_id
          description: Form ID
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '405':
          description: Invalid input
    
  /api/d1ec9c36-b1d9-4d6f-89d6-658dc324c2a1/f75e3879-0b28-4827-839e-f6342e7fe455/:
    post:
      tags:
        - test3
      summary: Add form data
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Form object
          required: true
          schema:
            $ref: '#/definitions/test3'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/test3'
        '405':
          description: Invalid input
    put:
      tags:
        - test3
      summary: Update form data
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Form object
          required: true
          schema:
            $ref: '#/definitions/test3'
      responses:
        '200':
          description: Successful operation
        '405':
          description: Invalid input
    get:
      tags: 
        - test3
      summary: Get form data
      produces: 
        - application/json
      parameters:
      - in: path
        name: tenant_id
        description: Form and data storage identifier
        schema:
        type: string
      - in: path
        name: form_id
        description: Form identifier
        schema:
        type: string
      - in: body
        required: false
        schema:
          $ref: '#/definitions/test3'
      responses:
        '201':
          description: Success
    delete:
      tags:
        - test3
      summary: Delete form data
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: tenant_id
          description: Tenant ID
          schema:
            type: string
        - in: path
          name: form_id
          description: Form ID
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '405':
          description: Invalid input
    
definitions:
  teest:
    type: object
    properties:
      teest:
        type: object
        properties:
          id:
            type: string
          user_updated:
            type: string
          user_created:
            type: string
          user_archived:
            type: string
          date_updated:
            type: string
          date_archived:
            type: string
          date_created:
            type: string
          textbox0:
            type: string
  test3:
    type: object
    properties:
      test3:
        type: object
        properties:
          id:
            type: string
          user_updated:
            type: string
          user_created:
            type: string
          user_archived:
            type: string
          date_updated:
            type: string
          date_archived:
            type: string
          date_created:
            type: string
          textbox0:
            type: string
          id:
            type: string
          user_updated:
            type: string
          user_created:
            type: string
          user_archived:
            type: string
          date_updated:
            type: string
          date_archived:
            type: string
          date_created:
            type: string
          textbox0:
            type: string
          textarea11:
            type: string
          undefined:
            type: string